# .github/dependabot.yml
version: 2
updates:

  # Define an anchor for common settings
  - &common_settings
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["all"]
        directories:
          - "**/deprecated"

  - package-ecosystem: "bundler"
    <<: *common_settings

  - package-ecosystem: "cargo"
    <<: *common_settings

  - package-ecosystem: "composer"
    <<: *common_settings

  - package-ecosystem: "devcontainers"
    <<: *common_settings

  - package-ecosystem: "docker"
    <<: *common_settings

  - package-ecosystem: "dotnet-sdk"
    <<: *common_settings

  - package-ecosystem: "mix"
    <<: *common_settings

  - package-ecosystem: "elm"
    <<: *common_settings

  - package-ecosystem: "gitsubmodule"
    <<: *common_settings

  - package-ecosystem: "github-actions"
    <<: *common_settings

  - package-ecosystem: "gomod"
    <<: *common_settings

  - package-ecosystem: "gradle"
    <<: *common_settings

  - package-ecosystem: "maven"
    <<: *common_settings

  - package-ecosystem: "npm"
    <<: *common_settings

  - package-ecosystem: "nuget"
    <<: *common_settings

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["all"]
        directories:
          - "**/deprecated"
      - dependency-name: "*"
        directories:
          - "**/requirements-27Aug2020.txt"
          - "**/requirements-19Mar2021.txt"

  - package-ecosystem: "pub"
    <<: *common_settings

  - package-ecosystem: "swift"
    <<: *common_settings

  - package-ecosystem: "terraform"
    <<: *common_settings
